name: Daily Update

on:
  schedule:
    # Run every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch latest executive orders
        run: npm run build
      
      - name: Check for changes
        id: check_changes
        run: |
          git add public/data.json
          if git diff --staged --quiet; then
            echo "No changes detected in data.json"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in data.json"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "Update executive orders data [skip ci]"
          git push
      
      - name: No changes to commit
        if: steps.check_changes.outputs.changes_detected == 'false'
        run: echo "No new executive orders found. Data is already up to date."
